'use client'
import { useParams } from 'next/navigation'
import { NextPage } from 'next'
import Head from 'next/head'
import DashboardLayout from '@/components/dashboard/dashboard-layout/dashboard-layout';
import { isAddress } from 'viem';
import NewDashboardLayout from '@/components/dashboard/dashboard-layout/new-dashboard-layout';

interface QueryParams {
  address: string;
}

const AddressPage: NextPage = () => {
  // Use the useRouter hook to access route parameters
  const params = useParams();

  // Ensure address exists and is a string
  if (!isAddress(params.address as string)) {
    return <div>Invalid address parameter.</div>;
  }

  return (
    <>
      <Head>
        <title>WalletApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <NewDashboardLayout address={params.address as `0x${string}`}/>
    </>
  )
}

export default AddressPage