import Head from 'next/head'
// import styles from '@/styles/dashboard.module.css'
// import NavBar from '@/components/common/navbar/navbar'
// import SideBar from '@/components/dashboard/sidebar/sidebar'
// import NftArea from '@/components/dashboard/nft-area/nft-area'
import DashboardLayout from '@/components/dashboard/dashboard-layout/dashboard-layout'


export default function Dashboard() {
  return (
    <>
      <Head>
        <title>WalletApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <div className={styles.dashboard} >
        <NavBar navbarGridTemplate={styles.navbarGridTemplate} />
        <SideBar sidebarGridTemplate={styles.sidebar} />
        <NftArea nftAreaGridTemplate={styles.content} /> 
      </div> */}
      <DashboardLayout />
    </>
  )
}
